window.JAKE_GIGS = {
  count: 101,
  venues: [
    { id: "ship", name: "The Ship", town: "Aveley", lat: 51.499, lng: 0.253 },
    { id: "dog", name: "The Dog & Partridge", town: "North Stifford", lat: 51.491, lng: 0.312 },
    { id: "chadwell", name: "Chadwell St Mary WMC", town: "Chadwell St Mary", lat: 51.481, lng: 0.37 },
    { id: "stifford", name: "Stifford Clays Social Club", town: "Stifford Clays", lat: 51.497, lng: 0.33 },
    { id: "tyrrells", name: "Tyrrells Hall Club", town: "Grays", lat: 51.478, lng: 0.325 },
    { id: "miro", name: "Miro Brasserie", town: "Upminster", lat: 51.557, lng: 0.25 },
    { id: "kervan", name: "Kervan Kitchen", town: "Brentwood", lat: 51.662, lng: 0.28 },
    { id: "corringham", name: "Corringham Social Club", town: "Corringham", lat: 51.523, lng: 0.46 },
    { id: "springhouse", name: "The Springhouse Club", town: "Corringham", lat: 51.525, lng: 0.455 },
    { id: "railway", name: "The Railway Tavern", town: "Stanford-le-Hope", lat: 51.514, lng: 0.424 },
    { id: "chalvedon", name: "Great Chalvedon Hall", town: "Pitsea", lat: 51.565, lng: 0.504 },
    { id: "ghyllgrove", name: "Ghyllgrove Club", town: "Basildon", lat: 51.577, lng: 0.465 },
    { id: "bluehouse", name: "Bluehouse Farm", town: "Laindon", lat: 51.574, lng: 0.418 },
    { id: "rayleigh", name: "Rayleigh Conservative Club", town: "Rayleigh", lat: 51.585, lng: 0.605 },
    { id: "poshboys", name: "Posh Boys Brewery Bar", town: "Wickford", lat: 51.612, lng: 0.53 },
    { id: "anchor", name: "The Anchor", town: "Canewdon", lat: 51.617, lng: 0.744 },
    { id: "canvey-rbl", name: "Canvey Royal British Legion", town: "Canvey Island", lat: 51.526, lng: 0.585 },
    { id: "sandy", name: "Sandy Bay", town: "Canvey Island", lat: 51.517, lng: 0.568 },
    { id: "kingspark", name: "Kings Park Residents Club", town: "Canvey Island", lat: 51.53, lng: 0.61 },
    { id: "flag", name: "The Flag Inn", town: "Wivenhoe", lat: 51.856, lng: 0.963 },
    { id: "whitehart-ing", name: "White Hart Inn", town: "Ingatestone", lat: 51.67, lng: 0.384 },
    { id: "whitehart-bor", name: "The White Hart", town: "Boreham", lat: 51.762, lng: 0.542 },
    { id: "loxford", name: "Loxford Club", town: "Ilford", lat: 51.555, lng: 0.09 },
    { id: "barking", name: "Barking United Services Club", town: "Barking", lat: 51.54, lng: 0.09 },
    { id: "pelly", name: "Pelly House", town: "Buckhurst Hill", lat: 51.626, lng: 0.042 },
    { id: "sw-ham", name: "South West Ham Labour Club", town: "Plaistow", lat: 51.522, lng: 0.018 },
    { id: "glamis", name: "Glamis Hall Club", town: "Wapping", lat: 51.508, lng: -0.048 },
    { id: "queens", name: "The Queen’s Head", town: "Stratford", lat: 51.542, lng: 0.003 },
    { id: "beckton", name: "The Beckton Arms", town: "Beckton", lat: 51.509, lng: 0.055 },
    { id: "globe", name: "Globe Town", town: "Bethnal Green", lat: 51.527, lng: -0.049 },
    { id: "tooke", name: "The Tooke Arms", town: "Limehouse", lat: 51.511, lng: -0.033 },
    { id: "stafford", name: "Stafford Street Friendship Club", town: "Limehouse", lat: 51.508, lng: -0.027 },
    { id: "bancroft", name: "The Bancroft Arms", town: "Mile End", lat: 51.523, lng: -0.04 },
    { id: "stjohns", name: "St John’s Centre", town: "Walworth", lat: 51.49, lng: -0.093 },
    { id: "bellingham", name: "Bellingham Ex Servicemen’s Club", town: "Bellingham", lat: 51.431, lng: -0.022 },
    { id: "hoe", name: "Hoe Street Club", town: "Walthamstow", lat: 51.588, lng: -0.02 },
    { id: "coppermill", name: "The Coppermill", town: "Walthamstow", lat: 51.581, lng: -0.04 },
    { id: "ponders", name: "Ponders End WMC", town: "Ponders End", lat: 51.645, lng: -0.036 },
    { id: "oldmanor", name: "The Old Manor", town: "Potters Bar", lat: 51.697, lng: -0.178 },
    { id: "sidcup", name: "Sidcup United Services Club", town: "Sidcup", lat: 51.426, lng: 0.103 },
    { id: "neweltham", name: "New Eltham Social Club", town: "New Eltham", lat: 51.438, lng: 0.071 },
    { id: "falconwood", name: "The Falconwood Club", town: "Welling", lat: 51.459, lng: 0.098 },
    { id: "bellegrove", name: "Bellegrove Social Club", town: "Welling", lat: 51.462, lng: 0.105 },
    { id: "westbeck", name: "West Beckenham Conservative Club", town: "Beckenham", lat: 51.405, lng: -0.04 },
    { id: "bromley-usc", name: "Bromley United Services Club", town: "Bromley", lat: 51.406, lng: 0.015 },
    { id: "summerfield", name: "The Summerfield Tavern", town: "Bromley", lat: 51.441, lng: 0.021 },
    { id: "gordon", name: "The Gordon Arms", town: "Chislehurst", lat: 51.412, lng: 0.075 },
    { id: "smokey", name: "Smokey Kitchen", town: "Orpington", lat: 51.376, lng: 0.099 },
    { id: "croydon", name: "Croydon Masonic Hall", town: "Croydon", lat: 51.38, lng: -0.09 },
    { id: "hartley", name: "Hartley Country Club", town: "Hartley", lat: 51.385, lng: 0.305 },
    { id: "perry", name: "Perry Street Conservative Club", town: "Northfleet", lat: 51.43, lng: 0.35 },
    { id: "stone", name: "Stone Street Club", town: "Maidstone", lat: 51.268, lng: 0.522 },
    { id: "bricklayers", name: "The Bricklayers Arms", town: "Aylesford", lat: 51.303, lng: 0.478 },
    { id: "bunters", name: "The Bunters", town: "Sittingbourne", lat: 51.34, lng: 0.749 },
    { id: "hoo", name: "Hoo Village Institute", town: "Hoo", lat: 51.42, lng: 0.558 },
    { id: "dovercastle", name: "The Dover Castle Inn", town: "Faversham", lat: 51.315, lng: 0.891 },
    { id: "dining", name: "The Dining Room", town: "Leysdown", lat: 51.399, lng: 0.923 },
    { id: "parkave", name: "Park Avenue Holiday Village", town: "Leysdown", lat: 51.397, lng: 0.918 },
    { id: "george", name: "The George", town: "Headcorn", lat: 51.169, lng: 0.627 },
    { id: "pagham", name: "Pagham Beach Club", town: "Pagham", lat: 50.77, lng: -0.745 },
    { id: "amalfi", name: "Amalfi Restaurant", town: "Ewell", lat: 51.351, lng: -0.249 },
    { id: "zeno", name: "Zeno Restaurant", town: "Horley", lat: 51.174, lng: -0.161 }
  ],
  upcoming: [
    { date: "2026-08-22", when: "Sat 22 Aug", venue: "Bromley United Services Club", town: "Bromley", time: "7.30pm" },
    { date: "2026-08-29", when: "Sat 29 Aug", venue: "Loxford Club", town: "Ilford", time: "9.00pm" },
    { date: "2026-08-30", when: "Sun 30 Aug", venue: "Glamis Hall Club", town: "Wapping", time: "3.00pm" },
    { date: "2026-09-04", when: "Fri 4 Sep", venue: "South West Ham Labour Club", town: "Plaistow", time: "8.30pm" },
    { date: "2026-09-06", when: "Sun 6 Sep", venue: "Tyrrells Hall Club", town: "Grays", time: "3.00pm" },
    { date: "2026-09-12", when: "Sat 12 Sep", venue: "Bellingham Ex Servicemen’s Club", town: "Bellingham", time: "8.30pm" },
    { date: "2026-09-13", when: "Sun 13 Sep", venue: "Pelly House", town: "Buckhurst Hill", time: "2.00pm" },
    { date: "2026-09-18", when: "Thu 18 Sep", venue: "The Old Manor", town: "Potters Bar", time: "8.00pm" },
    { date: "2026-09-19", when: "Sat 19 Sep", venue: "Stone Street Club", town: "Maidstone", time: "8.30pm" },
    { date: "2026-09-20", when: "Sun 20 Sep", venue: "The Bricklayers Arms", town: "Aylesford", time: "3.00pm" },
    { date: "2026-09-25", when: "Fri 25 Sep", venue: "The Summerfield Tavern", town: "Bromley", time: "8.00pm" },
    { date: "2026-09-26", when: "Sat 26 Sep", venue: "Pagham Beach Club", town: "Pagham", time: "4.00pm" },
    { date: "2026-09-27", when: "Sun 27 Sep", venue: "Ponders End WMC", town: "Ponders End", time: "8.30pm" },
    { date: "2026-10-04", when: "Sun 4 Oct", venue: "The Railway Tavern", town: "Stanford-le-Hope", time: "5.00pm" },
    { date: "2026-10-17", when: "Sat 17 Oct", venue: "West Beckenham Conservative Club", town: "Beckenham", time: "8.30pm" },
    { date: "2026-10-24", when: "Sat 24 Oct", venue: "Barking United Services Club", town: "Barking", time: "8.00pm" },
    { date: "2026-11-01", when: "Sun 1 Nov", venue: "Corringham Social Club", town: "Corringham", time: "8.15pm" },
    { date: "2026-11-08", when: "Sun 8 Nov", venue: "Glamis Hall Club", town: "Wapping", time: "3.00pm" },
    { date: "2026-12-05", when: "Sat 5 Dec", venue: "The Springhouse Club", town: "Corringham", time: "8.45pm" },
    { date: "2026-12-12", when: "Sat 12 Dec", venue: "Kings Park Residents Club", town: "Canvey Island", time: "8.30pm" },
    { date: "2026-12-13", when: "Sun 13 Dec", venue: "Bellingham Ex Servicemen’s Club", town: "Bellingham", time: "2.30pm" },
    { date: "2026-12-18", when: "Fri 18 Dec", venue: "Posh Boys Brewery Bar", town: "Wickford", time: "7.30pm" },
    { date: "2026-12-19", when: "Sat 19 Dec", venue: "Croydon Masonic Hall", town: "Croydon", time: "8.30pm" },
    { date: "2026-12-26", when: "Sat 26 Dec", venue: "The George", town: "Headcorn", time: "5.00pm" }
  ]
};
