window.JE_RECORDINGS = [
  {
    "id": "a-fool-such-as-i",
    "song": "A Fool Such As I",
    "original": "Elvis Presley / Hank Snow",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/01-a-fool-such-as-i.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "a-thing-called-love",
    "song": "A Thing Called Love",
    "original": "Johnny Cash / Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/02-a-thing-called-love.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "all-i-have-to-do-is-dream",
    "song": "All I Have To Do Is Dream",
    "original": "The Everly Brothers",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/03-all-i-have-to-do-is-dream.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "anyone-could-fall-in-love-with-you",
    "song": "Anyone Could Fall In Love With You",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/04-anyone-could-fall-in-love-with-you.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "are-you-lonesome-tonight",
    "song": "Are You Lonesome Tonight",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/05-are-you-lonesome-tonight.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "beyond-the-sea",
    "song": "Beyond The Sea",
    "original": "Bobby Darin",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/06-beyond-the-sea.mp3",
    "year": 2025,
    "featured": true,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "bitter-they-are-harder-they-fall",
    "song": "Bitter They Are, Harder They Fall",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/07-bitter-they-are-harder-they-fall.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "blue-hawaii",
    "song": "Blue Hawaii",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/08-blue-hawaii.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "blue-suede-shoes",
    "song": "Blue Suede Shoes",
    "original": "Carl Perkins / Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/09-blue-suede-shoes.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "can-t-help-falling-in-love",
    "song": "Can't Help Falling In Love",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/10-can-t-help-falling-in-love.mp3",
    "year": 2025,
    "featured": true,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "didja-ever",
    "song": "Didja Ever",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/11-didja-ever.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "dirty-dirty-feeling",
    "song": "Dirty Dirty Feeling",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/12-dirty-dirty-feeling.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "doin-the-best-i-can",
    "song": "Doin' The Best I Can",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/13-doin-the-best-i-can.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "don-t",
    "song": "Don't",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/14-don-t.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "dream-lover",
    "song": "Dream Lover",
    "original": "Bobby Darin",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/15-dream-lover.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "early-morning-rain",
    "song": "Early Morning Rain",
    "original": "Gordon Lightfoot / Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/16-early-morning-rain.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "echoes-of-love",
    "song": "Echoes Of Love",
    "original": "The Diamonds / Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/17-echoes-of-love.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "everyday",
    "song": "Everyday",
    "original": "Buddy Holly",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/18-everyday.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "for-the-good-times",
    "song": "For The Good Times",
    "original": "Kris Kristofferson / Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/19-for-the-good-times.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "from-a-jack-to-a-king",
    "song": "From A Jack To A King",
    "original": "Ned Miller / Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/20-from-a-jack-to-a-king.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "g-i-blues",
    "song": "G.I. Blues",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/21-g-i-blues.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "gently",
    "song": "Gently",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/22-gently.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "girl-of-mine",
    "song": "Girl Of Mine",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/23-girl-of-mine.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "give-me-the-right",
    "song": "Give Me The Right",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/24-give-me-the-right.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "got-a-lot-o-livin-to-do",
    "song": "Got a Lot of Livin' to Do",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/25-got-a-lot-o-livin-to-do.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "great-balls-of-fire",
    "song": "Great Balls Of Fire",
    "original": "Jerry Lee Lewis",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/26-great-balls-of-fire.mp3",
    "year": 2025,
    "featured": true,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "guess-things-happen-that-way",
    "song": "Guess Things Happen That Way",
    "original": "Johnny Cash / Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/27-guess-things-happen-that-way.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "hawaii-usa",
    "song": "Hawaii USA",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/28-hawaii-usa.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "home-is-where-the-heart-is",
    "song": "Home Is Where The Heart Is",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/29-home-is-where-the-heart-is.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "how-the-web-was-woven",
    "song": "How The Web Was Woven",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/30-how-the-web-was-woven.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "i-don-t-wanna-be-tied",
    "song": "I Don't Wanna be Tied",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/31-i-don-t-wanna-be-tied.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "i-feel-so-bad",
    "song": "I Feel So Bad",
    "original": "Chuck Willis / Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/32-i-feel-so-bad.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "i-feel-that-i-ve-known-you-forever",
    "song": "I Feel That I've Known You Forever",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/33-i-feel-that-i-ve-known-you-forever.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "i-got-lucky",
    "song": "I Got Lucky",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/34-i-got-lucky.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "i-gotta-know",
    "song": "I Gotta Know",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/35-i-gotta-know.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "i-want-to-be-free",
    "song": "I Want To Be Free",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/36-i-want-to-be-free.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "i-will-be-true",
    "song": "I Will Be True",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/37-i-will-be-true.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "i-ll-be-with-you-always",
    "song": "I'll Be With You Always",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/38-i-ll-be-with-you-always.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "i-m-falling-in-love-tonight",
    "song": "I'm Falling In Love Tonight",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/39-i-m-falling-in-love-tonight.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "i-ve-got-you-under-my-skin",
    "song": "I've Got You Under My Skin",
    "original": "Cole Porter / Frank Sinatra",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/40-i-ve-got-you-under-my-skin.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "i-wonder-why",
    "song": "I Wonder Why",
    "original": "Dion & The Belmonts",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/41-i-wonder-why.mp3",
    "year": 2025,
    "featured": true,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "if-i-can-dream",
    "song": "If I Can Dream",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/42-if-i-can-dream.mp3",
    "year": 2025,
    "featured": true,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "in-your-arms",
    "song": "In Your Arms",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/43-in-your-arms.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "it-hurts-me",
    "song": "It Hurts Me",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/44-it-hurts-me.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "it-s-a-long-lonely-highway",
    "song": "It's A Long Lonely Highway",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/45-it-s-a-long-lonely-highway.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "it-s-midnight",
    "song": "It's Midnight",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/46-it-s-midnight.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "king-creole",
    "song": "King Creole",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/47-king-creole.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "love-letters",
    "song": "Love Letters",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/48-love-letters.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "love-me",
    "song": "Love Me",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/49-love-me.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "loving-arms",
    "song": "Loving Arms",
    "original": "Kris Kristofferson / Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/50-loving-arms.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "mary-in-the-morning",
    "song": "Mary In The Morning",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/51-mary-in-the-morning.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "memphis-tennessee",
    "song": "Memphis Tennessee",
    "original": "Chuck Berry / Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/52-memphis-tennessee.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "moon-river",
    "song": "Moon River",
    "original": "Henry Mancini / Audrey Hepburn",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/53-moon-river.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "my-way",
    "song": "My Way",
    "original": "Frank Sinatra / Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/54-my-way.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "oh-boy",
    "song": "Oh Boy",
    "original": "Buddy Holly & The Crickets",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/55-oh-boy.mp3",
    "year": 2025,
    "featured": true,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "peggy-sue",
    "song": "Peggy Sue",
    "original": "Buddy Holly",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/56-peggy-sue.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "promised-land",
    "song": "Promised Land",
    "original": "Chuck Berry / Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/57-promised-land.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "put-the-blame-on-me",
    "song": "Put The Blame On Me",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/58-put-the-blame-on-me.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "return-to-sender",
    "song": "Return To Sender",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/59-return-to-sender.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "runaround-sue",
    "song": "Runaround Sue",
    "original": "Dion",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/60-runaround-sue.mp3",
    "year": 2025,
    "featured": true,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "she-s-not-you",
    "song": "She's Not You",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/61-she-s-not-you.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "shoppin-around",
    "song": "Shoppin' Around",
    "original": "Classic",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/62-shoppin-around.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "snowbird",
    "song": "Snowbird ",
    "original": "Anne Murray / Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/63-snowbird.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "solitaire",
    "song": "Solitaire",
    "original": "Classic",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/64-solitaire.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "something-blue",
    "song": "Something Blue",
    "original": "Classic",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/65-something-blue.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "stand-by-me",
    "song": "Stand By Me",
    "original": "Classic",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/66-stand-by-me.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "steppin-out-of-line",
    "song": "Steppin' Out Of Line ",
    "original": "Classic",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/67-steppin-out-of-line.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "stuck-on-you",
    "song": "Stuck On You",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/68-stuck-on-you.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "such-an-easy-question",
    "song": "Such An Easy Question",
    "original": "Classic",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/69-such-an-easy-question.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "that-s-all-right",
    "song": "That's All Right",
    "original": "Classic",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/70-that-s-all-right.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "the-first-time-ever-i-saw-your-face",
    "song": "The First Time Ever I Saw Your Face",
    "original": "Classic",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/71-the-first-time-ever-i-saw-your-face.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "the-impossible-dream",
    "song": "The Impossible Dream (Live)",
    "original": "Man of La Mancha / Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/72-the-impossible-dream.mp3",
    "year": 2025,
    "featured": true,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "the-wanderer",
    "song": "The Wanderer",
    "original": "Dion",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/73-the-wanderer.mp3",
    "year": 2025,
    "featured": true,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "tomorrow-never-comes",
    "song": "Tomorrow Never Comes (Take 2)",
    "original": "Classic",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/74-tomorrow-never-comes.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "treat-me-nice",
    "song": "Treat Me Nice",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/75-treat-me-nice.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "true-love-ways",
    "song": "True Love Ways",
    "original": "Buddy Holly",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/76-true-love-ways.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "where-did-they-go-lord",
    "song": "Where Did They Go Lord (Take 2)",
    "original": "Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/77-where-did-they-go-lord.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "whole-lotta-shakin-goin-on",
    "song": "Whole Lotta' Shakin' Goin' On",
    "original": "Classic",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/78-whole-lotta-shakin-goin-on.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "words",
    "song": "Words",
    "original": "Classic",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/79-words.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "you-don-t-have-to-say-you-love-me",
    "song": "You Don't Have To Say You Love Me",
    "original": "Dusty Springfield / Elvis Presley",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/80-you-don-t-have-to-say-you-love-me.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "you-don-t-know-me",
    "song": "You Dont Know Me",
    "original": "Classic",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/81-you-don-t-know-me.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "you-got-it",
    "song": "You Got It",
    "original": "Classic",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/82-you-got-it.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "you-ll-never-walk-alone",
    "song": "You'll Never Walk Alone",
    "original": "Classic",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/83-you-ll-never-walk-alone.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "you-ve-lost-that-loving-feeling",
    "song": "You've Lost That Loving Feeling",
    "original": "The Righteous Brothers",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/84-you-ve-lost-that-loving-feeling.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg"
  },
  {
    "id": "xmas-it-s-the-most-wonderful-time-of-the-year",
    "song": "It's The Most Wonderful Time Of The Year",
    "original": "Andy Williams",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/xmas-it-s-the-most-wonderful-time-of-the-year.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg",
    "album": "Christmas"
  },
  {
    "id": "xmas-let-it-snow",
    "song": "Let It Snow",
    "original": "Vaughn Monroe / Frank Sinatra",
    "source": "file",
    "kind": "audio",
    "src": "/audio/favourites/xmas-let-it-snow.mp3",
    "year": 2025,
    "featured": false,
    "poster": "/images/studio-gold.jpg",
    "album": "Christmas"
  }
];
